
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package simuladorconsola;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COPY = 5;
  public static final int READ = 23;
  public static final int MENOS = 18;
  public static final int CREATEFE = 13;
  public static final int LIST = 6;
  public static final int BACKDIR = 16;
  public static final int READ_WRITE = 26;
  public static final int MOVEPATH = 12;
  public static final int CONCAT = 2;
  public static final int NFILE = 22;
  public static final int MANPERMISO = 11;
  public static final int WRITE = 24;
  public static final int SPACE = 15;
  public static final int LISTDET = 7;
  public static final int LISTHIDE = 8;
  public static final int READ_EXECUTE = 28;
  public static final int RECURSIVE = 14;
  public static final int PFILE = 21;
  public static final int EOF = 0;
  public static final int DIRECTION = 3;
  public static final int NEWDIR = 19;
  public static final int error = 1;
  public static final int DELETEDIR = 10;
  public static final int READ_WRITE_EXECUTE = 29;
  public static final int DELETE = 9;
  public static final int WRITE_EXECUTE = 27;
  public static final int RENAMEF = 4;
  public static final int EXECUTE = 25;
  public static final int PDIRECTORY = 20;
  public static final int MAS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCAT",
  "DIRECTION",
  "RENAMEF",
  "COPY",
  "LIST",
  "LISTDET",
  "LISTHIDE",
  "DELETE",
  "DELETEDIR",
  "MANPERMISO",
  "MOVEPATH",
  "CREATEFE",
  "RECURSIVE",
  "SPACE",
  "BACKDIR",
  "MAS",
  "MENOS",
  "NEWDIR",
  "PDIRECTORY",
  "PFILE",
  "NFILE",
  "READ",
  "WRITE",
  "EXECUTE",
  "READ_WRITE",
  "WRITE_EXECUTE",
  "READ_EXECUTE",
  "READ_WRITE_EXECUTE"
  };
}

